### ISSUE TITLE
rails g payola:install not working with Rails 5.1

### ISSUE THREAD

**Issue by naterexw** [payolapayments/payola#321]
In Rails 5, after running 
```
rails g payola:install
```
and then running
```
rake db:migrate
```
produces the following error message:
```
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreatePayolaSales < ActiveRecord::Migration[4.2]
-e:1:in `<main>'
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreatePayolaSales < ActiveRecord::Migration[4.2]
-e:1:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by naterexw** [comment]
I forked the gem and updated the migration files to use "ActiveRecord::Migration[5.1]".  

Seems to fix the problem, I created a pull request: https://github.com/payolapayments/payola/pull/322

**Comment by alekseenko** [comment]
@naterexw The error is already fixed. Just use master branch instead of RubyGems version

**Comment by jscho13** [comment]
@alekseenko how do you use master branch? I've run `bundle update` and am using payola-payments 1.5.0. I still see this error.

**Comment by jscho13** [comment]
This issue still isn't fixed for me. When deploying to Heroku the migrations fail despite using payola payments 1.5.0
